name: build-and-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0


      - name: Setup Zola ⚙️
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.20.0

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install Dependencies 📦
        run: npm install

      - name: Build Site 🏗️
        run: |
          zola build
          touch public/.nojekyll

      - name: Deploy to GitHub Pages 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
