name: Sync and Deploy

on:
  # 允许手动push触发
  push:
    branches:
      - main
      - master
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - deploy
  # 允许手动触发
  workflow_dispatch:

# 设置GITHUB_TOKEN权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保只有一个部署任务同时运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'npm'

      - name: 安装依赖
        run: |
          export TZ='Asia/Shanghai'
          npm ci

      - name: 拉取Notion文档
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          npm run sync

      - name: 清理并构建Hexo网站
        run: |
          npm run clean
          npm run build

      - name: 添加.nojekyll文件
        run: |
          touch ./public/.nojekyll

      - name: 配置GitHub Pages
        uses: actions/configure-pages@v4

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
